apiVersion: v2
name: load-balancer
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: aws-load-balancer-controller
    version: 1.4.7
    repository: https://aws.github.io/eks-charts
